name: ball_in_cup
task: dmc_ball_in_cup_catch
collection_task: ball_in_cup/catch
dataset: ball_in_cup_catch
planning_horizon: 25
state_fields:
  position: [0, 1, 2, 3]
  velocity: [0, 1, 2, 3]

goal:
  geometry: box
  tolerance: [0.025, 0.025]

action:
  kind: continuous
  shape: [2]
