defaults:
  - _base_

deter: 512
hidden: 128
discrete: 16
depth: 16
units: 128
act: 'SiLU'
norm: True
compile: False

rssm:
  core: mamba3
  warmup: 0
  mamba3:
    n_layers: 1
    d_state: 32
    expand: 1
    headdim: 64
    is_mimo: False
    mimo_rank: 1
    chunk_size: 16
    is_outproj_norm: False
