tdmpc2_root: ${TDMPC2_DIR}
output_dir: ${DMC_EXPERT_DATA_DIR}
local_output_dir: /content/dmc_expert

num_episodes: 4000
checkpoint_seed: 1
seed: 1

action_repeat: 2
max_episode_steps: 500

save_images: false
image_size: 64

expert:
  mpc: false

refresh_seconds: 10
recent_log_lines: 25
progress_every: 25
start_from_scratch: true

tasks:
  - task: cartpole/swingup
    difficulty: easy
  - task: walker/walk
    difficulty: medium
  - task: humanoid/run
    difficulty: hard
