defaults:
  - dmc_experiment
  - model: size_small
  - _self_

logdir: logdir/dmc_expert/${scenario.name}/${model.rssm.core}/seed_${seed}/${now:%Y-%m-%d}/${now:%H-%M-%S}

training:
  expert:
    enabled: true

replay:
  batch_size: 16

model:
  hidden: 713
