task: ${scenario.task}
env_num: 16
eval_episode_num: 10
action_repeat: 2
train_ratio: 512
time_limit: 1000

seed: ${seed}
eval_seed: 1000000
device: ${device}

size: [64, 64]
dataset_root: ${oc.env:DMC_EXPERT_VISION_DATA_DIR,data/dmc_expert_vision}
proprio: null
model_io:
  observations:
    image:
      - ${env.size.0}
      - ${env.size.1}
      - 3
  action: ${scenario.action}
